version: "3.9"
services:
  nginx:
    build:
      context: "./nginx/"
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/castrpet/assets/
    ports:
      - "80:80"
      - "443:80"
    depends_on: 
      - django
  django:
    build: ./web/
    restart: always
    command: >
      sh -c "uwsgi --ini CastrPet.uwsgi.ini"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/var/www/castrpet/assets/
volumes:
  uwsgi_data:
  web_static:
