name: Configure IAM credentials - AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/iam/**'

permissions:
  id-token: write 
  contents: read

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::914256152987:role/GitHubActionsRole

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: |
          cd terraform/iam
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform/iam
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform/iam
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform/iam
          terraform apply -auto-approve