name: Create Federation - GitHub and AWS

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'terraform/iam/**'

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Terraform Init
        run: |
          cd terraform/iam
          terraform init

      - name: Terraform Validate
        run: |
          cd terraform/iam
          terraform validate

      - name: Terraform Plan
        run: |
          cd terraform/iam
          terraform plan

      - name: Terraform Apply
        run: 
          cd terraform/iam
          terraform apply -auto-approve